<a href="https://colab.research.google.com/github/B3nzeneKnight/LetsGitStarted/blob/main/ETP_Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [10]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [31]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [12]:
import pandas as pd
df=pd.read_csv('gdrive/My Drive/Datasets/breast_cancer_data.csv')

In [33]:
df.head(5)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

Data Preprocessing

In [28]:
#X = df.drop(labels=['id','diagnosis','texture_mean','perimeter_mean','area_mean','smoothness_mean','compactness_mean','concavity_mean','concave points_mean','texture_worst','perimeter_worst'],axis=1)

In [30]:
from sklearn.feature_selection import VarianceThreshold

In [34]:
X=df.drop(['diagnosis'], axis=1)
y=df['diagnosis']

In [38]:
from sklearn.model_selection import train_test_split
# separate dataset into train and test
X_train, X_test, y_train, y_test = train_test_split(
    X,y,test_size=0.3,random_state=0)

X_train.shape, X_test.shape

((398, 32), (171, 32))

Feature Selection

In [39]:
var_thres=VarianceThreshold(threshold=0)
var_thres.fit(X_train)

/usr/local/lib/python3.7/dist-packages/sklearn/feature_selection/_variance_threshold.py:104: RuntimeWarning: Degrees of freedom <= 0 for slice.
  self.variances_ = np.nanvar(X, axis=0)
/usr/local/lib/python3.7/dist-packages/sklearn/feature_selection/_variance_threshold.py:112: RuntimeWarning: All-NaN slice encountered
  self.variances_ = np.nanmin(compare_arr, axis=0)


VarianceThreshold(threshold=0)

In [42]:
### Finding non constant features
sum(var_thres.get_support())

31

In [43]:
# Lets Find non-constant features 
len(X_train.columns[var_thres.get_support()])

31

In [44]:
constant_columns = [column for column in X_train.columns
                    if column not in X_train.columns[var_thres.get_support()]]

print(len(constant_columns))

1


In [45]:
p=X_train.drop(constant_columns,axis=1)
p

id  radius_mean  texture_mean  perimeter_mean  area_mean  \
478     911685       11.490         14.59           73.99      404.9   
303     892657       10.490         18.61           66.86      334.3   
155    8711003       12.250         17.94           78.27      460.3   
186     874217       18.310         18.58          118.60     1041.0   
101     862722        6.981         13.43           43.79      143.5   
..         ...          ...           ...             ...        ...   
277    8911670       18.810         19.98          120.90     1102.0   
9     84501001       12.460         24.04           83.97      475.9   
359  901034301        9.436         18.32           59.82      278.6   
192     875099        9.720         18.22           60.73      288.1   
559     925291       11.510         23.93           74.52      403.5   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
478          0.10460           0.08228         0.05308              0.01969   
303          0.10680           0.06678         0.02297              0.01780   
155          0.08654           0.06679         0.03885              0.02331   
186          0.08588           0.08468         0.08169              0.05814   
101          0.11700           0.07568         0.00000              0.00000   
..               ...               ...             ...                  ...   
277          0.08923           0.05884         0.08020              0.05843   
9            0.11860           0.23960         0.22730              0.08543   
359          0.10090           0.05956         0.02710              0.01406   
192          0.06950           0.02344         0.00000              0.00000   
559          0.09261           0.10210         0.11120              0.04105   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
478         0.1779  ...        12.400          21.90            82.04   
303         0.1482  ...        11.060          24.54            70.76   
155         0.1970  ...        13.590          25.22            86.60   
186         0.1621  ...        21.310          26.36           139.20   
101         0.1930  ...         7.930          19.54            50.41   
..             ...  ...           ...            ...              ...   
277         0.1550  ...        19.960          24.30           129.00   
9           0.2030  ...        15.090          40.68            97.65   
359         0.1506  ...        12.020          25.02            75.79   
192         0.1653  ...         9.968          20.83            62.25   
559         0.1388  ...        12.480          37.16            82.28   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
478       467.6           0.13520            0.20100          0.25960   
303       375.4           0.14130            0.10440          0.08423   
155       564.2           0.12170            0.17880          0.19430   
186      1410.0           0.12340            0.24450          0.35380   
101       185.2           0.15840            0.12020          0.00000   
..          ...               ...                ...              ...   
277      1236.0           0.12430            0.11600          0.22100   
9         711.4           0.18530            1.05800          1.10500   
359       439.6           0.13330            0.10490          0.11440   
192       303.8           0.07117            0.02729          0.00000   
559       474.2           0.12980            0.25170          0.36300   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
478               0.07431          0.2941                  0.09180  
303               0.06528          0.2213                  0.07842  
155               0.08211          0.3113                  0.08132  
186               0.15710          0.3206                  0.06938  
101               0.00000          0.2932                  0.09382  
..                    ...     

In [47]:
p.shape

(398, 31)

Feature Scaling

In [50]:
import matplotlib as plt
import seaborn as sns
%matplotlib inline

In [52]:
df=pd.read_csv('gdrive/My Drive/Datasets/breast_cancer_data.csv')
df

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

In [56]:
data = df.drop(["id","Unnamed: 32"],axis=1)
data

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0           M        17.99         10.38          122.80     1001.0   
1           M        20.57         17.77          132.90     1326.0   
2           M        19.69         21.25          130.00     1203.0   
3           M        11.42         20.38           77.58      386.1   
4           M        20.29         14.34          135.10     1297.0   
..        ...          ...           ...             ...        ...   
564         M        21.56         22.39          142.00     1479.0   
565         M        20.13         28.25          131.20     1261.0   
566         M        16.60         28.08          108.30      858.1   
567         M        20.60         29.33          140.10     1265.0   
568         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.2419  ...        25.380          17.33           184.60   
1           0.1812  ...        24.990          23.41           158.80   
2           0.2069  ...        23.570          25.53           152.50   
3           0.2597  ...        14.910          26.50            98.87   
4           0.1809  ...        22.540          16.67           152.20   
..             ...  ...           ...            ...              ...   
564         0.1726  ...        25.450          26.40           166.10   
565         0.1752  ...        23.690          38.25           155.00   
566         0.1590  ...        18.980          34.12           126.70   
567         0.2397  ...        25.740          39.42           184.60   
568         0.1587  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0        2019.0           0.16220            0.66560           0.7119   
1        1956.0           0.12380            0.18660           0.2416   
2        1709.0           0.14440            0.42450           0.4504   
3         567.7           0.20980            0.86630           0.6869   
4        1575.0           0.13740            0.20500           0.4000   
..          ...               ...                ...              ...   
564      2027.0           0.14100            0.21130           0.4107   
565      1731.0           0.11660            0.19220           0.3215   
566      1124.0           0.11390            0.30940           0.3403   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...         

In [ ]:
#sns.pairplot(data)

Normalization

Linear Regression

In [46]:
#Using Simple radius to predict via SLR

In [60]:
df1 = df.loc[ : , 'diagnosis' : 'radius_mean']
df1

diagnosis  radius_mean
0           M        17.99
1           M        20.57
2           M        19.69
3           M        11.42
4           M        20.29
..        ...          ...
564         M        21.56
565         M        20.13
566         M        16.60
567         M        20.60
568         B         7.76

[569 rows x 2 columns]

In [76]:
df1['diagnosis'] = df['diagnosis'].replace(['M'],1)
df1['diagnosis'] = df['diagnosis'].replace(['B'],0)
df1

diagnosis  radius_mean
0            1        17.99
1            1        20.57
2            1        19.69
3            1        11.42
4            1        20.29
..         ...          ...
564          1        21.56
565          1        20.13
566          1        16.60
567          1        20.60
568          0         7.76

[569 rows x 2 columns]

In [ ]:
from sklearn.linear_model import LinearRegression
target1= df1.loc[ : , :'diagnosis']
target1

In [72]:
linear_reg=LinearRegression()
linear_reg.fit(df1[['radius_mean']],df1.diagnosis)

LinearRegression()

In [73]:
linear_reg.predict([[20.00]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([0.9613025])

In [75]:
linear_reg.predict([[21.00]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([1.0615491])

In [77]:
linear_reg.predict([[14.00]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([0.35982292])

In [79]:
linear_reg.predict([[11.00]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([0.05908312])